package com.SaikuSecurityIBMTest.controller;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;

import com.SaikuSecurityIBMTest.domain.core.GpUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class GpBaseController {

	private GpUser theUser;
	protected final Log logger = LogFactory.getLog(this.getClass());

	public UserDetails getUser(){
		Authentication authentication = SecurityContextHolder.getContext()
				.getAuthentication();
		UserDetails user = null;
		if (authentication != null) {
			Object principal = authentication.getPrincipal();
			if (principal instanceof UserDetails) {
				user = (UserDetails) principal;
				System.out.println("Loggedin user: " + user.getUsername());
				System.out.println("Logged in User rolE"+ user.getAuthorities());
			}
		}else{
			System.out.println("Enered as null data or not equal Instance"+authentication.getAuthorities());
		}
		return user;
	}


}