/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/


USE saikusecurityibmtest;

CREATE TABLE GpAuthority (id bigint(20) NOT NULL AUTO_INCREMENT, authority varchar(255) DEFAULT NULL, PRIMARY KEY (id)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
INSERT INTO GpAuthority VALUES (1,'GpUser');
INSERT INTO GpAuthority VALUES (2,'GpAdmin');
CREATE TABLE GpUser (id bigint(20) NOT NULL AUTO_INCREMENT,accestype varchar(255) DEFAULT NULL,firstName varchar(255) DEFAULT NULL,languagepreference varchar(255) DEFAULT NULL,lastName varchar(255) DEFAULT NULL,lastaccess datetime DEFAULT NULL,licenseid varchar(255) DEFAULT NULL,middleName varchar(255) DEFAULT NULL,mustresetpassword varchar(255) DEFAULT NULL,newuser bit(1) DEFAULT NULL,password varchar(255) DEFAULT NULL,phonenumber varchar(255) DEFAULT NULL, primaryemail varchar(255) DEFAULT NULL, screenname varchar(255) DEFAULT NULL, startdate datetime DEFAULT NULL, username varchar(255) DEFAULT NULL, PRIMARY KEY (id)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
INSERT INTO GpUser VALUES (1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'','12345',NULL,NULL,NULL,NULL,'test');
CREATE TABLE GpUser_GpAuthority ( GpUser_id bigint(20) NOT NULL, roles_id bigint(20) NOT NULL, PRIMARY KEY (GpUser_id,roles_id), CONSTRAINT FK_c7kyumqvtqtl74s6ci1vkhywp FOREIGN KEY (GpUser_id) REFERENCES GpUser (id), CONSTRAINT FK_qqk29t20hlrhy5v62t5jrxdkk FOREIGN KEY (roles_id) REFERENCES GpAuthority (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO GpUser_GpAuthority VALUES (1,1);

